eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 11000
spring:
  application:
    name: zuul-server
zuul:
  routes:
    user-api:
      path: /user/**
      serviceId: user-api
    feign-api:
      path: /feign/**
      serviceId: feign-api
    hystrix-api:
      path: /hystrix/**
      serviceId: hystrix-api
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  prefix: /api
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000